/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICapsuleRegistry,
  ICapsuleRegistryInterface,
} from "../../../../contracts/types/Interfaces.sol/ICapsuleRegistry";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "message",
            type: "string",
          },
          {
            internalType: "string",
            name: "readKey",
            type: "string",
          },
          {
            internalType: "string",
            name: "revealKey",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "unlockTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct PrivateCapsuleCreateParams",
        name: "createParams",
        type: "tuple",
      },
    ],
    name: "addPrivateCapsuleRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "message",
            type: "string",
          },
          {
            internalType: "string",
            name: "revealKey",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "unlockTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct PublicCapsuleCreateParams",
        name: "createParams",
        type: "tuple",
      },
    ],
    name: "addPublicCapsuleRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "authenticateCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "deauthenticateCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "readKey",
            type: "string",
          },
        ],
        internalType: "struct ReadPrivateCapsuleParams",
        name: "readParams",
        type: "tuple",
      },
    ],
    name: "readPrivateCapsuleRecord",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "string",
                name: "message",
                type: "string",
              },
              {
                internalType: "bytes32",
                name: "readMessageHash",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "revealMessageHash",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "unlockTimestamp",
                type: "uint256",
              },
            ],
            internalType: "struct PrivateCapsuleParams",
            name: "data",
            type: "tuple",
          },
          {
            internalType: "enum CapsuleStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct PrivateCapsuleData",
        name: "result",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
        ],
        internalType: "struct ReadPublicCapsuleParams",
        name: "readParams",
        type: "tuple",
      },
    ],
    name: "readPublicCapsuleRecord",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "string",
                name: "message",
                type: "string",
              },
              {
                internalType: "bytes32",
                name: "revealMessageHash",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "unlockTimestamp",
                type: "uint256",
              },
            ],
            internalType: "struct PublicCapsuleParams",
            name: "data",
            type: "tuple",
          },
          {
            internalType: "enum CapsuleStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct PublicCapsuleData",
        name: "result",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "revealKey",
            type: "string",
          },
        ],
        internalType: "struct RevealPrivateCapsuleParams",
        name: "revealParams",
        type: "tuple",
      },
    ],
    name: "revealPrivateCapsuleRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "revealKey",
            type: "string",
          },
        ],
        internalType: "struct RevealPublicCapsuleParams",
        name: "revealParams",
        type: "tuple",
      },
    ],
    name: "revealPublicCapsuleRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICapsuleRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ICapsuleRegistryInterface {
    return new Interface(_abi) as ICapsuleRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICapsuleRegistry {
    return new Contract(address, _abi, runner) as unknown as ICapsuleRegistry;
  }
}
