/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrivateCapsuleMetadata,
  IPrivateCapsuleMetadataInterface,
} from "../../../../contracts/types/Interfaces.sol/IPrivateCapsuleMetadata";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "readKey",
            type: "string",
          },
        ],
        internalType: "struct ReadPrivateCapsuleParams",
        name: "readParams",
        type: "tuple",
      },
    ],
    name: "readPrivateCapsuleRecord",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "string",
                name: "message",
                type: "string",
              },
              {
                internalType: "bytes32",
                name: "readMessageHash",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "revealMessageHash",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "unlockTimestamp",
                type: "uint256",
              },
            ],
            internalType: "struct PrivateCapsuleParams",
            name: "data",
            type: "tuple",
          },
          {
            internalType: "enum CapsuleStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct PrivateCapsuleData",
        name: "result",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPrivateCapsuleMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IPrivateCapsuleMetadataInterface {
    return new Interface(_abi) as IPrivateCapsuleMetadataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrivateCapsuleMetadata {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPrivateCapsuleMetadata;
  }
}
