/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CapsuleManagerBaseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authenticateCaller"
      | "deauthenticateCaller"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeployDependencies"
      | "OwnershipTransferred"
      | "PrivateCapsuleCreated"
      | "PrivateCapsuleRevealed"
      | "PublicCapsuleCreated"
      | "PublicCapsuleRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authenticateCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthenticateCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authenticateCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthenticateCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DeployDependenciesEvent {
  export type InputTuple = [
    registry: AddressLike,
    publicCapsuleCollection: AddressLike,
    privateCapsuleCollection: AddressLike
  ];
  export type OutputTuple = [
    registry: string,
    publicCapsuleCollection: string,
    privateCapsuleCollection: string
  ];
  export interface OutputObject {
    registry: string;
    publicCapsuleCollection: string;
    privateCapsuleCollection: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateCapsuleCreatedEvent {
  export type InputTuple = [tokenId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [tokenId: bigint, owner: string];
  export interface OutputObject {
    tokenId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateCapsuleRevealedEvent {
  export type InputTuple = [tokenId: BigNumberish, informant: AddressLike];
  export type OutputTuple = [tokenId: bigint, informant: string];
  export interface OutputObject {
    tokenId: bigint;
    informant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicCapsuleCreatedEvent {
  export type InputTuple = [tokenId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [tokenId: bigint, owner: string];
  export interface OutputObject {
    tokenId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicCapsuleRevealedEvent {
  export type InputTuple = [tokenId: BigNumberish, informant: AddressLike];
  export type OutputTuple = [tokenId: bigint, informant: string];
  export interface OutputObject {
    tokenId: bigint;
    informant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CapsuleManagerBase extends BaseContract {
  connect(runner?: ContractRunner | null): CapsuleManagerBase;
  waitForDeployment(): Promise<this>;

  interface: CapsuleManagerBaseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authenticateCaller: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  deauthenticateCaller: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authenticateCaller"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deauthenticateCaller"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DeployDependencies"
  ): TypedContractEvent<
    DeployDependenciesEvent.InputTuple,
    DeployDependenciesEvent.OutputTuple,
    DeployDependenciesEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PrivateCapsuleCreated"
  ): TypedContractEvent<
    PrivateCapsuleCreatedEvent.InputTuple,
    PrivateCapsuleCreatedEvent.OutputTuple,
    PrivateCapsuleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PrivateCapsuleRevealed"
  ): TypedContractEvent<
    PrivateCapsuleRevealedEvent.InputTuple,
    PrivateCapsuleRevealedEvent.OutputTuple,
    PrivateCapsuleRevealedEvent.OutputObject
  >;
  getEvent(
    key: "PublicCapsuleCreated"
  ): TypedContractEvent<
    PublicCapsuleCreatedEvent.InputTuple,
    PublicCapsuleCreatedEvent.OutputTuple,
    PublicCapsuleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PublicCapsuleRevealed"
  ): TypedContractEvent<
    PublicCapsuleRevealedEvent.InputTuple,
    PublicCapsuleRevealedEvent.OutputTuple,
    PublicCapsuleRevealedEvent.OutputObject
  >;

  filters: {
    "DeployDependencies(address,address,address)": TypedContractEvent<
      DeployDependenciesEvent.InputTuple,
      DeployDependenciesEvent.OutputTuple,
      DeployDependenciesEvent.OutputObject
    >;
    DeployDependencies: TypedContractEvent<
      DeployDependenciesEvent.InputTuple,
      DeployDependenciesEvent.OutputTuple,
      DeployDependenciesEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PrivateCapsuleCreated(uint256,address)": TypedContractEvent<
      PrivateCapsuleCreatedEvent.InputTuple,
      PrivateCapsuleCreatedEvent.OutputTuple,
      PrivateCapsuleCreatedEvent.OutputObject
    >;
    PrivateCapsuleCreated: TypedContractEvent<
      PrivateCapsuleCreatedEvent.InputTuple,
      PrivateCapsuleCreatedEvent.OutputTuple,
      PrivateCapsuleCreatedEvent.OutputObject
    >;

    "PrivateCapsuleRevealed(uint256,address)": TypedContractEvent<
      PrivateCapsuleRevealedEvent.InputTuple,
      PrivateCapsuleRevealedEvent.OutputTuple,
      PrivateCapsuleRevealedEvent.OutputObject
    >;
    PrivateCapsuleRevealed: TypedContractEvent<
      PrivateCapsuleRevealedEvent.InputTuple,
      PrivateCapsuleRevealedEvent.OutputTuple,
      PrivateCapsuleRevealedEvent.OutputObject
    >;

    "PublicCapsuleCreated(uint256,address)": TypedContractEvent<
      PublicCapsuleCreatedEvent.InputTuple,
      PublicCapsuleCreatedEvent.OutputTuple,
      PublicCapsuleCreatedEvent.OutputObject
    >;
    PublicCapsuleCreated: TypedContractEvent<
      PublicCapsuleCreatedEvent.InputTuple,
      PublicCapsuleCreatedEvent.OutputTuple,
      PublicCapsuleCreatedEvent.OutputObject
    >;

    "PublicCapsuleRevealed(uint256,address)": TypedContractEvent<
      PublicCapsuleRevealedEvent.InputTuple,
      PublicCapsuleRevealedEvent.OutputTuple,
      PublicCapsuleRevealedEvent.OutputObject
    >;
    PublicCapsuleRevealed: TypedContractEvent<
      PublicCapsuleRevealedEvent.InputTuple,
      PublicCapsuleRevealedEvent.OutputTuple,
      PublicCapsuleRevealedEvent.OutputObject
    >;
  };
}
