/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as collection from "./collection";
export type { collection };
import type * as factoryUtils from "./factory-utils";
export type { factoryUtils };
import type * as registry from "./registry";
export type { registry };
import type * as types from "./types";
export type { types };
import type * as utils from "./utils";
export type { utils };
export type { CapsuleManager } from "./CapsuleManager";
export type { CapsuleManagerBase } from "./CapsuleManagerBase";
