/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as inheritance from "./inheritance";
export { PrivateCapsuleERC721__factory } from "./PrivateCapsuleERC721__factory";
export { PublicCapsuleERC721__factory } from "./PublicCapsuleERC721__factory";
