/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IDeployFactoryInterface extends Interface {
  getFunction(nameOrSignature: "deployAllInstances"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployAllInstances",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployAllInstances",
    data: BytesLike
  ): Result;
}

export interface IDeployFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IDeployFactory;
  waitForDeployment(): Promise<this>;

  interface: IDeployFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployAllInstances: TypedContractMethod<
    [adminUser: AddressLike],
    [
      [string, string, string] & {
        registryInstance: string;
        publicCapsuleCollectionInstance: string;
        privateCapsuleCollectionInstance: string;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployAllInstances"
  ): TypedContractMethod<
    [adminUser: AddressLike],
    [
      [string, string, string] & {
        registryInstance: string;
        publicCapsuleCollectionInstance: string;
        privateCapsuleCollectionInstance: string;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
