/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type ReadPrivateCapsuleParamsStruct = {
  tokenId: BigNumberish;
  readKey: string;
};

export type ReadPrivateCapsuleParamsStructOutput = [
  tokenId: bigint,
  readKey: string
] & { tokenId: bigint; readKey: string };

export type PrivateCapsuleParamsStruct = {
  message: string;
  readMessageHash: BytesLike;
  revealMessageHash: BytesLike;
  unlockTimestamp: BigNumberish;
};

export type PrivateCapsuleParamsStructOutput = [
  message: string,
  readMessageHash: string,
  revealMessageHash: string,
  unlockTimestamp: bigint
] & {
  message: string;
  readMessageHash: string;
  revealMessageHash: string;
  unlockTimestamp: bigint;
};

export type PrivateCapsuleDataStruct = {
  data: PrivateCapsuleParamsStruct;
  status: BigNumberish;
};

export type PrivateCapsuleDataStructOutput = [
  data: PrivateCapsuleParamsStructOutput,
  status: bigint
] & { data: PrivateCapsuleParamsStructOutput; status: bigint };

export interface IPrivateCapsuleMetadataInterface extends Interface {
  getFunction(nameOrSignature: "readPrivateCapsuleRecord"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "readPrivateCapsuleRecord",
    values: [ReadPrivateCapsuleParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "readPrivateCapsuleRecord",
    data: BytesLike
  ): Result;
}

export interface IPrivateCapsuleMetadata extends BaseContract {
  connect(runner?: ContractRunner | null): IPrivateCapsuleMetadata;
  waitForDeployment(): Promise<this>;

  interface: IPrivateCapsuleMetadataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  readPrivateCapsuleRecord: TypedContractMethod<
    [readParams: ReadPrivateCapsuleParamsStruct],
    [PrivateCapsuleDataStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "readPrivateCapsuleRecord"
  ): TypedContractMethod<
    [readParams: ReadPrivateCapsuleParamsStruct],
    [PrivateCapsuleDataStructOutput],
    "view"
  >;

  filters: {};
}
