/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DocumentVerifier } from "./DocumentVerifier";
export * as factories from "./factories";
export { DocumentVerifier__factory } from "./factories/DocumentVerifier__factory";
