/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as inheritance from "./inheritance";
export type { inheritance };
export type { PrivateCapsuleERC721 } from "./PrivateCapsuleERC721";
export type { PublicCapsuleERC721 } from "./PublicCapsuleERC721";
